### ISSUE TITLE
Unable to use graph commands

### ISSUE THREAD

**Issue by gopar** [ag91/code-compass#19]
When I try a command like `c/show-complexity-over-commits`. I get the following error:

>   Sorry, didn't recognize that command!
  Type graph --help to view common commands.

Any help is appreciated.

**Comment by gopar** [comment]
Looks like I installed the wrong `graph-cli`
I installed this one:
https://github.com/graphprotocol/graph-cli#installation

Perhaps docs could provide links to the dependencies so this doesn't happen.
Thanks!

**Comment by ag91** [comment]
oh curious: you installed without pip? Let me add the reference now
