### ISSUE TITLE
Publish on MELPA

### ISSUE THREAD

**Issue by sir4ur0n** [ag91/code-compass#20]
Hi,

Have you considered publishing `code-compass` on MELPA or GNU ELPA? That would make it simpler to use :pray:

**Comment by ag91** [comment]
Mmm, it is just some refactoring effort I need to go through (I think). The target would be Melpa, because ELPA is only for free software as far as I know, and this depends on non-free bits.

**Comment by ag91** [comment]
https://github.com/melpa/melpa/pull/8417: crossing fingers this will be accepted

**Comment by ag91** [comment]
done
