### ISSUE TITLE
Some `defcustom`s are not correctly passed to async code

### ISSUE THREAD

**Issue by sir4ur0n** [ag91/code-compass#21]
Some `defcustom`s are not passed to async code. E.g.:

```lisp
(setq c/code-maat-command "foobar")
(c/show-hotspots)
```

will incorrectly use the default value of `c/code-maat-command` rather than `"foobar"` e.g. in `c/run-code-maat`.

I managed to make it work with something like that:
```diff
@@ -263,6 +263,7 @@
    `(lambda ()
       (setq load-path ',load-path)
       (load-file ,(symbol-file command))
+      (setq c/code-maat-command ,c/code-maat-command)
       (let ((browse-url-browser-function 'browse-url-generic)
             (browse-url-generic-program ,c/preferred-browser))
         (funcall ',command ,repository ,date)))
```

But I don't know if this is the idiomatic way to go.

Or how is one supposed to customize those `defcustoms` otherwise?

**Comment by ag91** [comment]
hey thanks for the issue. Your solution sounds right! Do you want to make  a PR or send me the whole patch, so your contribution can stay in the history? Otherwise I can apply the fix as well :)
Happy 2023!

**Comment by sir4ur0n** [comment]
Happy 2023 to you too :smile: 

I'd rather you apply the fix directly, because there may be other variables that need to be passed through to the async function, but I haven't noticed them because I don't need them. I don't mind my name not staying in history :smile:
