### ISSUE TITLE
Incorrect assumption about `/tmp` vs `/data`

### ISSUE THREAD

**Issue by sir4ur0n** [ag91/code-compass#23]
The code assumes that:
* `/tmp` is used when using `java -jar xxx.jar` value for `c/code-maat-command`
* `/data` is used when using the Docker value for `c/code-maat-command`

An example of such an assumption:
https://github.com/ag91/code-compass/blob/main/code-compass.el#L336

I use neither a Java command nor Docker (I provide directly a `code-maat` executable via Nix).
In most places the default used is `/tmp` **when not Docker**, but in this line of code (and maybe others?) it uses `/data` **when not Java**.

It means that my set-up breaks because it sometimes uses `/tmp` and sometimes `/data`.

How about the path where dummy directories are created becomes configurable?
* it makes less assumptions about the running system (e.g. what if one does not have `/tmp`? Or not write-permission?)
* even for those using Docker, it becomes possible to fine-tune the location

In a similar way, I also suggest (but we can move that in another issue if you will) making the global path where `code-compass` downloads stuff (e.g. `dependencies/d3.v3.min2js`) as customizable please :pray: 
A use case I have is that I provide `code-compass` Git repository as a Nix package, i.e. it ends up in a read-only directory, which then crashes when `code-compass` tries to write to it.

**Comment by ag91** [comment]
right, so 3 new defcustom should fix this issue. Let me try

**Comment by ag91** [comment]
done, can you let me know if this addresses your issue? In case we can close this

**Comment by sir4ur0n** [comment]
Thank you!

I am surprised by this change:
https://github.com/ag91/code-compass/commit/39fc3235e81045c8db938daead71675121d399ad#diff-403bd57b4035bd6080ca58474a307ed13b4b3ac3e6642dbc918f711609ad8368R335
```diff
- (unless (or (not maat-jar-p) (file-exists-p (c/expand-file-name source-file)))
+ (unless (or (not docker-command-p) (file-exists-p (c/expand-file-name source-file)))
```
Shouldn't it be this instead?
```elisp
(if (and (maat-jar-p) (not (file-exists-p (c/expand-file-name source-file))))
```
which, by the way, I think better carries the meaning: "If we use the JAR command for `maat-jar`, and the JAR is not in the download directory, then we download it".

What do you think?

From a user perspective, I think it also prevents users from providing/using their own JAR but that's a different problem (and to be frank, one that does not impact me :sweat_smile: )

**Comment by sir4ur0n** [comment]
Besides my comment above - which does not impact me - the problem seems to be resolved for me with the latest commit, thank you!

**Comment by ag91** [comment]
> Thank you!
> 
> I am surprised by this change: [39fc323#diff-403bd57b4035bd6080ca58474a307ed13b4b3ac3e6642dbc918f711609ad8368R335](https://github.com/ag91/code-compass/commit/39fc3235e81045c8db938daead71675121d399ad#diff-403bd57b4035bd6080ca58474a307ed13b4b3ac3e6642dbc918f711609ad8368R335)
> 
> ```diff
> - (unless (or (not maat-jar-p) (file-exists-p (c/expand-file-name source-file)))
> + (unless (or (not docker-command-p) (file-exists-p (c/expand-file-name source-file)))
> ```
> 
> Shouldn't it be this instead?
> 
> ```emacs-lisp
> (if (and (maat-jar-p) (not (file-exists-p (c/expand-file-name source-file))))
> ```
> 
> which, by the way, I think better carries the meaning: "If we use the JAR command for `maat-jar`, and the JAR is not in the download directory, then we download it".
> 
> What do you think?
> 
> From a user perspective, I think it also prevents users from providing/using their own JAR but that's a different problem (and to be frank, one that does not impact me sweat_smile )

Thanks, I confused myself. Right, I don't think there has been a user yet who wants to swap jars ;)
