### ISSUE TITLE
Permission issue while copying scripts

### ISSUE THREAD

**Issue by sir4ur0n** [ag91/code-compass#24]
To reproduce:
1. `M-x c/show-coupling-graph-sync`
2. `M-x c/show-coupling-graph-sync`

The second time, it fails:
```
c/copy-file: Opening output file: Permission denied, /tmp/code-compass-<REDACTED>/coupling_csv_as_edge_bundling.py
```

This is because most of the script files are read-only (linux permissions).

Probably these should have read-write permissions in the Git repo?

**Comment by ag91** [comment]
right, maybe it is just a matter of modifying the postInstall clause in your nix recipe no?

**Comment by sir4ur0n** [comment]
Hmmm no, all files in the Nix store are read-only, this is not negotiable or modifiable in any way :sweat_smile: This is a fundamental aspect of Nix.

I can think of 2 ways:
* stop copying the scripts, and instead just run them from the `c/path-to-code-compass` location
* we add a `set-file-modes` command after `copy-file` in `c/copy-file`. I think this would be transparent for non-Nix users

I think the first suggestion is the most sensible, right? Or is there a reason to copy/duplicate the scripts that I am missing?

**Comment by ag91** [comment]
mmm, I like the copying as you can see what scripts were used for your analysis in the artefact directory. Going to add the set-file-modes

**Comment by ag91** [comment]
hopefully this solves your issue

**Comment by sir4ur0n** [comment]
I think you missed `c/generate-host-edge-bundling-html` :sweat_smile: These also trigger an error on second execution

**Comment by sir4ur0n** [comment]
PS: I notice that from a fresh start (after I remove `/tmp/code-compass-<REDACTED>`):
* if I run `c/show-coupling-graph`, everything works as expected, including opening the browser
* if I run `c/show-coupling-graph-sync` (useful because with the async mode, the log messages are not displayed in `*Messages*` buffer), then it correctly generates all the files in `/tmp/code-compass-<REDACTED>` but it does not open the browser :thinking: 

Is that the expected behavior? :sweat_smile:

**Comment by ag91** [comment]
> I think you missed `c/generate-host-edge-bundling-html` sweat_smile These also trigger an error on second execution

those file shouldn't be executable as the browser should deal with them. What error did you get?

**Comment by ag91** [comment]
> * if I run `c/show-coupling-graph`, everything works as expected, including opening the browser
> * if I run `c/show-coupling-graph-sync` (useful because with the async mode, the log messages are not displayed in `*Messages*` buffer), then it correctly generates all the files in `/tmp/code-compass-<REDACTED>` but it does not open the browser thinking
> 
> Is that the expected behavior

expected: the async-run is opening the server. I used the sync analyses for debugging mostly. If I have time I will redesign that

**Comment by sir4ur0n** [comment]
> those file shouldn't be executable as the browser should deal with them. What error did you get?

On second execution of `c/show-coupling-graph-sync`, `c/generate-host-edge-bundling-html` is executed a second time, which copies the `edge-bundling` files. So similarly to the other files, if they don't have the `w` permission, the second copying fails.

**Comment by ag91** [comment]
lol sorry, working on this in the evening means that I am very slow at understanding what is going on. I just needed read write permission. Fixed both issues you raised: thanks for spotting this through Nix.
