### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by gopar** [ag91/code-compass#25]
Hey, thanks for the package. I see great potential for this! \o/

One thing I noticed is that everything is prefixed with `c/` which is not common among package development.
prefix would ideally be `code-compass-` (bit verbose but that is the norm).

Are you open to updating?
I can make PR and still keep backwards compatibility (can be done with `defalias`)

**Comment by ag91** [comment]
yes, please: that is one of the steps required for #20 but I hadn't the time to handle it yet.
A PR would be greatly appreciated :)
