### ISSUE TITLE
Is everything running locally?

### ISSUE THREAD

**Issue by alphaxmachine** [ag91/code-compass#43]
Stupid question: does any data get sent to external services? 
Wondering if this tool can be applied also on company resources / if anyone has done it before.

**Comment by ag91** [comment]
oh, not stupid at all. There was no need to send data outside of your computer: 
code-maat just transforms git-log data into csv.

I added some csv->html+js transformation to show it nicely (according to how the original author showed them in his book)

**Comment by alphaxmachine** [comment]
great! Thank you!
